__version__ = '0.0.1'

from .compression_strategies import MzSingleStringDeltaCompressionIntensityHexSeparateBrotliUrl as MsMsUrlCompressor
from .compression_strategies import MzSingleStringDeltaCompressionIntensityHexSeparateBrotliB85 as MsMsB85Compressor
